# Generated by Django 4.1.1 on 2022-12-28 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_rename_id_hospitalfee_hospitalfee_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clinicfee", old_name="id", new_name="ClinicFee_id",
        ),
    ]
