# Generated by Django 4.1.1 on 2022-12-28 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_rename_id_clinicfee_clinicfee_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="labfee", old_name="id", new_name="LabFee_id",
        ),
    ]
