# Generated by Django 4.1.1 on 2022-12-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_rename_id_labfee_labfee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disease",
            name="clinic",
            field=models.ManyToManyField(
                blank=True, related_name="diseases", to="base.clinic"
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="hospital",
            field=models.ManyToManyField(
                blank=True, related_name="diseases", to="base.hospital"
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="lab",
            field=models.ManyToManyField(
                blank=True, related_name="diseases", to="base.lab"
            ),
        ),
    ]
