export const LAB_LIST_REQUEST = 'LAB_LIST_REQUEST'
export const LAB_LIST_SUCCESS = 'LAB_LIST_SUCCESS'
export const LAB_LIST_FAIL = 'LAB_LIST_FAIL'

export const LAB_DETAILS_REQUEST = 'LAB_DETAILS_REQUEST'
export const LAB_DETAILS_SUCCESS = 'LAB_DETAILS_SUCCESS'
export const LAB_DETAILS_FAIL = 'LAB_DETAILS_FAIL'

export const LAB_CREATE_REVIEW_REQUEST = 'LAB_CREATE_REVIEW_REQUEST'
export const LAB_CREATE_REVIEW_SUCCESS = 'LAB_CREATE_REVIEW_SUCCESS'
export const LAB_CREATE_REVIEW_FAIL = 'LAB_CREATE_REVIEW_FAIL'
export const LAB_CREATE_REVIEW_RESET = 'LAB_CREATE_REVIEW_RESET'

export const LAB_DELETE_REQUEST = 'LAB_DELETE_REQUEST'
export const LAB_DELETE_SUCCESS = 'LAB_DELETE_SUCCESS'
export const LAB_DELETE_FAIL = 'LAB_DELETE_FAIL'

export const LAB_CREATE_REQUEST = 'LAB_CREATE_REQUEST'
export const LAB_CREATE_SUCCESS = 'LAB_CREATE_SUCCESS'
export const LAB_CREATE_FAIL = 'LAB_CREATE_FAIL'
export const LAB_CREATE_RESET = 'LAB_CREATE_RESET'

export const LAB_UPDATE_REQUEST = 'LAB_UPDATE_REQUEST'
export const LAB_UPDATE_SUCCESS = 'LAB_UPDATE_SUCCESS'
export const LAB_UPDATE_FAIL = 'LAB_UPDATE_FAIL'
export const LAB_UPDATE_RESET = 'LAB_UPDATE_RESET'